#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: guides
#          predicates:
#            - Path=/guides/**
#            - After=2022-09-07T00:00:00.000-00:00[Asia/Tehran]
#          uri: https://spring.io